### ISSUE TITLE
Error when disabling skips

### ISSUE THREAD

**Issue by MAYAS3** [Jovp/fixupunet#1]
Hello,

I am trying to use FixUpUnet without skip links. However, I get a channel size mismatch between the convolution weights and the feature map during upsampling when the number of channels is supposed to be reduced the first time.

I think it might be due to the fact that when `skips=False` no `FixupConvModule()` is added to the upsampling layers (only `nn.Upsample()` and `FixupResidualChain()` layers are added). This prevents the feature map's number of channels from changing when it's supposed to.

Am I missing something?

Code to replicate error:

```python
cfg = DictConfig(
        {
            "feat": 32,
            "in_feat": 3,
            "out_feat": 3,
            "down_layers": 5,
            "identity_layers": 3,
            "bottleneck_layers": 6,
            "skips": False,
            "act_fn": "relu",
            "out_act_fn": "none",
            "max_feat": 256,
            "script_submodules": True,
            "dim": 2,
        }
    )
net = FixUpUnet(cfg)
net(torch.rand((4, 3, 256, 256)))
```

P.s: thanks for the package. It's quite useful!

**Comment by Jovp** [comment]
Hello!

Thanks a lot for your contribution!
This commit should fix the issue, I haven't been using the network without skip links in a long time. Will make sure to test from now on.
https://github.com/Jovp/fixupunet/commit/8095aee2e26bf485e470b1a2d55bc8ef8252580d

Julien
